# Generated by Django 5.2.7 on 2025-11-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messages_app", "0002_rename_timestamp_message_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created_at"]},
        ),
    ]
