# Generated by Django 5.2.7 on 2025-11-13 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messages_app", "0003_alter_conversation_options_alter_message_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="deleted_for",
            field=models.ManyToManyField(
                blank=True,
                related_name="deleted_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
