# Generated by Django 5.2.7 on 2025-11-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0002_alter_category_options_ad_category_category_icon_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ad",
            old_name="category",
            new_name="categorie",
        ),
    ]
