# Generated by Django 5.2.7 on 2025-11-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0003_rename_category_ad_categorie"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Categorie",
        ),
    ]
