# Generated by Django 5.2.7 on 2025-11-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0004_rename_category_categorie"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="ads/"),
        ),
        migrations.AddField(
            model_name="ad",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="ads/"),
        ),
    ]
