# Generated by Django 5.2.7 on 2025-11-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0005_ad_image2_ad_image3"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="annee_mise_en_circulation",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ad",
            name="annee_modele",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ad",
            name="carburant",
            field=models.CharField(
                blank=True,
                choices=[
                    ("essence", "Essence"),
                    ("diesel", "Diesel"),
                    ("electrique", "Électrique"),
                    ("hybride", "Hybride"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="kilometrage",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ad",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ad",
            name="marque",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ad",
            name="transmission",
            field=models.CharField(
                blank=True,
                choices=[("manuelle", "Manuelle"), ("automatique", "Automatique")],
                max_length=50,
                null=True,
            ),
        ),
    ]
