# Generated by Django 5.2.7 on 2025-11-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0006_ad_annee_mise_en_circulation_ad_annee_modele_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="nombre_pieces",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ad",
            name="superficie",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Superficie du bien en m²",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="type_offre",
            field=models.CharField(
                blank=True,
                choices=[("location", "Location"), ("vente", "Vente")],
                help_text="Spécifie si le bien est en vente ou en location",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="zone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ad",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="ad_images/"),
        ),
        migrations.AlterField(
            model_name="ad",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="ad_images/"),
        ),
    ]
