# Generated by Django 5.2.7 on 2025-11-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "annonces",
            "0007_ad_nombre_pieces_ad_superficie_ad_type_offre_ad_zone_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
