# Generated by Django 5.2.7 on 2025-11-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0008_alter_ad_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
