# Generated by Django 5.2.7 on 2025-11-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0009_ad_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="premium",
            field=models.BooleanField(default=False),
        ),
    ]
