# Generated by Django 5.2.7 on 2025-11-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0010_ad_premium"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorie",
            name="icon",
            field=models.CharField(default="📦", max_length=50),
        ),
    ]
